"use strict";
exports.__esModule = true;
var CategoryManager_1 = require("../Business/Concrate/CategoryManager");
var Category_1 = require("../Entities/Category");
var categories = new CategoryManager_1.CategoryManager();
console.log(categories.GetCategory());
console.log("------------------------");
var myCategory = new Category_1.Category();
myCategory.id = 6;
myCategory.name = "modem";
categories.AddCategory(myCategory);
console.log(categories.GetCategory());
console.log("------------------------");
myCategory.name = "cameras";
categories.UpdateCategory(myCategory);
console.log(categories.GetCategory());
console.log("------------------------");
categories.DeleteCategory(myCategory.id);
console.log(categories.GetCategory());
